---
galaxy_info:
  author: admin
  description: Install Vector agent for host metrics collection
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

dependencies: []
